/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DSC.JROficina.Apresentacao;

import DSC.JROficina.Aplicacao.Peca;
import DSC.JROficina.Aplicacao.Repositorio;
import DSC.JROficina.Persistencia.PecaDAO;
import DSC.JROficina.Persistencia.PecaDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigo
 */
public class AdcPeca extends javax.swing.JDialog {

    Peca filtro = new Peca();
    Repositorio<Peca> repositorio = Repositorios.getPecaRepositorio();
    private boolean confirmado = false;
    Peca pecas;
    private int diferencia;
    
    
    //1 compra
    //2 venda
    public AdcPeca(java.awt.Frame parent, boolean modal, int diferencia) {
        super(parent, modal);
        initComponents();
        rolQtde.setValue(1);
        this.diferencia = diferencia;
    }
    
    public AdcPeca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rolQtde.setValue(1);
    }

    public boolean isConfirmado() {
        return confirmado;
    }

    public void setConfirmado(boolean confirmado) {
        this.confirmado = confirmado;
    }

    public Peca getPecas() {
        return pecas;
    }

    public void setPecas(Peca pecas) {
        this.pecas = pecas;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusca = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        btnBusca = new javax.swing.JButton();
        BtnAdcPeca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rolQtde = new javax.swing.JSpinner();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Peça");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nome:");

        tblBusca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblBusca);

        btnBusca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBusca.setText("Buscar");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        BtnAdcPeca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnAdcPeca.setText("Adicionar Peça");
        BtnAdcPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdcPecaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Quantidade: ");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rolQtde.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rolQtde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rolQtdeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBusca))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rolQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(BtnAdcPeca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(txtNome)
                    .addComponent(btnBusca))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rolQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAdcPeca)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        this.buscar();
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void BtnAdcPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdcPecaActionPerformed
        int x = 0;
        x = retornaIdSelecionado();
        if(diferencia == 1){
            if(x > 0){      
                if(((Integer) rolQtde.getValue()) > 0){
                    pecas = repositorio.Abrir(x);
                    int h = pecas.getQtde();
                    pecas.setQtde(0);
                    pecas.setQtde((Integer) rolQtde.getValue());
                    setConfirmado(true);
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "A quantidade deve ser maior que 0", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Selecione uma  peça", "Erro", JOptionPane.ERROR_MESSAGE); 
            }
        }else{
            if(x > 0){      
                if(((Integer) rolQtde.getValue()) > 0){
                    pecas = repositorio.Abrir(x);
                    
                    if(pecas.getQtde() >= ((Integer) rolQtde.getValue())){
                        pecas.setQtde(0);
                        pecas.setQtde((Integer) rolQtde.getValue());
                        setConfirmado(true);
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Estoque insuficiente!", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "A quantidade deve ser maior que 0", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Selecione uma  peça", "Erro", JOptionPane.ERROR_MESSAGE); 
            }
     
            
        }
    }//GEN-LAST:event_BtnAdcPecaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setConfirmado(false);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rolQtdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rolQtdeStateChanged
         if(((Integer)rolQtde.getValue()) == 0){
            JOptionPane.showMessageDialog(null, "O numero minimo deve ser 1!", "Erro", JOptionPane.ERROR_MESSAGE);
            rolQtde.setValue(1);
        }// TODO add your handling code here:
    }//GEN-LAST:event_rolQtdeStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdcPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdcPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdcPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdcPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdcPeca dialog = new AdcPeca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdcPeca;
    private javax.swing.JButton btnBusca;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner rolQtde;
    private javax.swing.JTable tblBusca;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

public void buscar(){
        limpaFiltro();
        
        preencheFiltro();
        
        List<Peca> listagem = new ArrayList<>();
        listagem = repositorio.Buscar(filtro);
        preencheTabela(listagem);
    }

public Peca adcPeca(){
        int x = retornaIdSelecionado();
        Peca p = new Peca();
        PecaDAO pp = null;
        p = pp.Abrir(x);
        p.setQtde((Integer)rolQtde.getValue());
        
        return p;
    }

    public int retornaIdSelecionado() {
       int linha = -1;
       linha = tblBusca.getSelectedRow();
       int id = 0;
       
       if(linha >= 0)
            id = Integer.parseInt(tblBusca.getModel().getValueAt(linha,0).toString());
        
       return id;
    }
    
    public void preencheFiltro() {
        if(!txtNome.getText().isEmpty())
            filtro.setNome(txtNome.getText());
    }

    public void preencheTabela(List<Peca> listagem) {
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("ID");
        modelo.addColumn("Nome");    
        modelo.addColumn("Descrição");
        modelo.addColumn("Estoque");
        modelo.addColumn("Valor Unitario Compra");
        modelo.addColumn("Marca");
        
         for(Peca c : listagem){
            Vector linha = new Vector();
            linha.add(c.getId());
            linha.add(c.getNome());
            linha.add(c.getDesc());
            linha.add(c.getQtde());
            linha.add(c.getValor_venda());
            linha.add(c.getMarca());
            
            modelo.addRow(linha);
            
        }    
        tblBusca.setModel(modelo);
    }

    public void limpaFiltro() {
        filtro.setNome(null);
        filtro.setId(0);
        filtro.setDesc(null);
        filtro.setQtde(-1);
        filtro.setValor_compra(-1);
        filtro.setValor_venda(-1);
        filtro.setFornecedor(null);
        filtro.setMarca(null);
    }
    





}
