/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DSC.JROficina.Apresentacao;

import DSC.JROficina.Aplicacao.Cliente;
import DSC.JROficina.Aplicacao.ClienteRepositorio;
import DSC.JROficina.Aplicacao.Moto;
import DSC.JROficina.Aplicacao.MotoRepositorio;
import DSC.JROficina.Aplicacao.Peca;
import DSC.JROficina.Aplicacao.Repositorio;
import DSC.JROficina.Aplicacao.Servico;
import DSC.JROficina.Aplicacao.StatusTransacao;
import DSC.JROficina.Aplicacao.Venda;
import DSC.JROficina.Aplicacao.VendaRepositorio;
import DSC.JROficina.Aplicacao.ViolacaoRegrasNegocioException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rodrigo
 */
public class PagamentoVenda extends TelaEdicao<Venda> {
    
    protected Repositorio<Peca> p;
    protected List<Peca> pecas;
    protected List<Servico> servicos;
    protected Peca pe;
    protected Servico se;
    protected SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy");
    protected float tot = 0;
    protected Date data;  
    Cliente c;
    Moto m;
    
    protected ClienteRepositorio clientes = Repositorios.getClienteRepositorio();
    protected MotoRepositorio motos = Repositorios.getMotoRepositorio();
    protected VendaRepositorio vendadao = Repositorios.getVendaRepositorio();
    
    public PagamentoVenda(int l) {
        initComponents();
        
        entidade = vendadao.Abrir(l);
        txtPago.setText("0");
        txtTroco.setText("0");
        pe = new Peca();
        txtTroco.setEnabled(false);
        txtRestante.setEnabled(false);
        txtParc.setEnabled(false);
        txtTotal.setEnabled(false);
        rolParcelas.setEnabled(false);
        txtVencimento.setEnabled(false);
        txtPago.setEnabled(false);
        formatarDate = new SimpleDateFormat("dd/MM/yyyy");
        this.carregaCampos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtPago = new javax.swing.JTextField();
        txtRestante = new javax.swing.JTextField();
        txtVencimento = new javax.swing.JTextField();
        txtValorP = new javax.swing.JTextField();
        txtProx = new javax.swing.JTextField();
        rolParcelas = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtParc = new javax.swing.JTextField();

        setTitle("Pagamento");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Valor Total:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Valor Pago:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Valor Restante:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Parcelas Restantes:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Vencimeto:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Valor do Pagamento:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Proximo Venciemento:");

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtPago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagoActionPerformed(evt);
            }
        });

        txtRestante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtVencimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtValorP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtProx.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        rolParcelas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Troco:");

        txtTroco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Valor Parcelas:");

        txtParc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParc))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTroco))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProx))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorP))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVencimento))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rolParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRestante))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPago))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rolParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtParc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtValorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtProx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            carregaObjeto();
        } catch (ViolacaoRegrasNegocioException ex) {
            Logger.getLogger(PagamentoVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        super.Salvar();
    }//GEN-LAST:event_jButton1ActionPerformed

    @Override
    public void carregaCampos() {
        c = (Cliente) entidade.getAliado();
        m = entidade.getVeiculo();
        servicos = entidade.getServicos();
        pecas = entidade.getPecas();
        txtPago.setText(String.valueOf(entidade.getValor_pago()));
        txtTroco.setText("0");
        txtTotal.setText(String.valueOf(entidade.getValor()));
        txtVencimento.setText(String.valueOf(entidade.getVencimento()));
        rolParcelas.setValue(entidade.getParcelas());
        pecas = entidade.getPecas();
        if(entidade.getValor() <= entidade.getValor_pago()){
            txtRestante.setText("0");
            txtParc.setText("0");
        }else{ 
            txtRestante.setText(String.valueOf(entidade.getValor() - entidade.getValor_pago()));
            txtParc.setText(String.valueOf((entidade.getValor() - entidade.getValor_pago()) / entidade.getParcelas()));
        }
    }

    @Override
    public void carregaObjeto() throws ViolacaoRegrasNegocioException {
       entidade.setPecas(pecas);
       entidade.setServicos(servicos);
       entidade.setData(data);       
        try {
            entidade.setVencimento((Date) formatarDate.parseObject(txtProx.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(CompraEditar.class.getName()).log(Level.SEVERE, null, ex);
        }
       entidade.setValor(Float.valueOf(txtTotal.getText()));
       entidade.setValor_parc(Float.valueOf(txtParc.getText()));
       entidade.setParcelas(((Integer) rolParcelas.getValue()) - 1);
       entidade.setAliado(c);
       float z = Float.valueOf(txtValorP.getText());
       float k = Float.valueOf(txtPago.getText());
       float y = Float.valueOf(txtParc.getText());
       entidade.setValor_pago((z + k) - y);
       if(Float.valueOf(txtPago.getText()) >= (Float.valueOf(txtTotal.getText())))
           entidade.setStatus(StatusTransacao.PAGO);
       else
           entidade.setStatus(StatusTransacao.PENDENTE);
       entidade.setTipo(2);
       entidade.setVeiculo(m);
    }

    @Override
    public boolean verificarCamposObrigatorios() {
        return !txtValorP.getText().isEmpty() || !txtProx.getText().isEmpty();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner rolParcelas;
    private javax.swing.JTextField txtPago;
    private javax.swing.JTextField txtParc;
    private javax.swing.JTextField txtProx;
    private javax.swing.JTextField txtRestante;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtValorP;
    private javax.swing.JTextField txtVencimento;
    // End of variables declaration//GEN-END:variables
}
