/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DSC.JROficina.Apresentacao;

import DSC.JROficina.Aplicacao.Aplicacao;
import DSC.JROficina.Aplicacao.Usuario;

/**
 *
 * @author Rodrigo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    
    TelaLogin telalogin;
    Usuario p;

    public void setTelaLogin(TelaLogin telalogin){
        this.telalogin = telalogin; 
    }
    
    public TelaPrincipal(Usuario p) {
        
        if(!Aplicacao.isLogged()){
            if(telalogin == null)
                telalogin = new TelaLogin();
            
            telalogin.setVisible(true);
            this.setVisible(false);
            this.p = p;
            return;          
        }
        
        initComponents();
        if(p.getTipo().getId() == 2)
            mnuUsuario.setVisible(false);
    }
    
     public TelaPrincipal() {
        
        if(!Aplicacao.isLogged()){
            if(telalogin == null)
                telalogin = new TelaLogin();
            
            telalogin.setVisible(true);
            this.setVisible(false);
         
            return;          
        }
        
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        btnSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        MnuFornecedores = new javax.swing.JMenuItem();
        mnuUsuario = new javax.swing.JMenuItem();
        mnuPecas = new javax.swing.JMenuItem();
        MnuServicos = new javax.swing.JMenuItem();
        mnuMotos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuB = new javax.swing.JMenuItem();
        mnuV = new javax.swing.JMenu();
        mnuVA = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        mnuCadastro.setText("Cadastros");
        mnuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroActionPerformed(evt);
            }
        });

        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuClientes);

        MnuFornecedores.setText("Fornecedores");
        MnuFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuFornecedoresActionPerformed(evt);
            }
        });
        mnuCadastro.add(MnuFornecedores);

        mnuUsuario.setText("Usuarios");
        mnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarioActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuUsuario);

        mnuPecas.setText("Peças");
        mnuPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPecasActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuPecas);

        MnuServicos.setText("Servicos");
        MnuServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuServicosActionPerformed(evt);
            }
        });
        mnuCadastro.add(MnuServicos);

        mnuMotos.setText("Motos");
        mnuMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMotosActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuMotos);

        jMenuBar1.add(mnuCadastro);

        jMenu2.setText("Compras");

        mnuB.setText("Buscar");
        mnuB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBActionPerformed(evt);
            }
        });
        jMenu2.add(mnuB);

        jMenuBar1.add(jMenu2);

        mnuV.setText("Vendas");
        mnuV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVActionPerformed(evt);
            }
        });

        mnuVA.setText("Buscar");
        mnuVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVAActionPerformed(evt);
            }
        });
        mnuV.add(mnuVA);

        jMenuBar1.add(mnuV);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(672, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnSair)
                .addGap(0, 505, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
       ClienteBuscar tela = new ClienteBuscar(Repositorios.getClienteRepositorio(), ClienteEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroActionPerformed
        ClienteBuscar tela = new ClienteBuscar(Repositorios.getClienteRepositorio(), ClienteEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuCadastroActionPerformed

    private void MnuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuFornecedoresActionPerformed
        FornecedorBuscar tela = new FornecedorBuscar(Repositorios.getFornecedorRepositorio(), FornecedorEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_MnuFornecedoresActionPerformed

    private void mnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioActionPerformed
        
        
        UsuarioBuscar tela = new UsuarioBuscar(Repositorios.getUsuarioRepositorio(), UsuarioEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuUsuarioActionPerformed

    private void mnuPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPecasActionPerformed
      PecaBuscar tela = new PecaBuscar(Repositorios.getPecaRepositorio(), PecaEditar.class);
        
        this.add(tela);
        tela.setVisible(true);  
    }//GEN-LAST:event_mnuPecasActionPerformed

    private void mnuMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMotosActionPerformed
       MotoBuscar tela = new MotoBuscar(Repositorios.getMotoRepositorio(), MotoEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuMotosActionPerformed

    private void MnuServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuServicosActionPerformed
       ServicoBuscar tela = new ServicoBuscar(Repositorios.getServicoRepositorio(), ServicoEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_MnuServicosActionPerformed

    private void mnuBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBActionPerformed
        CompraBuscar tela = new CompraBuscar(Repositorios.getCompraRepositorio(), CompraEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuBActionPerformed

    private void mnuVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVActionPerformed
        VendaBuscar tela = new VendaBuscar(Repositorios.getVendaRepositorio(), VendaEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuVActionPerformed

    private void mnuVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVAActionPerformed
        VendaBuscar tela = new VendaBuscar(Repositorios.getVendaRepositorio(), VendaEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuVAActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        telalogin = new TelaLogin();
            
            telalogin.setVisible(true);
            this.setVisible(false);
            this.p = p;
            return;          
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuFornecedores;
    private javax.swing.JMenuItem MnuServicos;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuB;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuMotos;
    private javax.swing.JMenuItem mnuPecas;
    private javax.swing.JMenuItem mnuUsuario;
    private javax.swing.JMenu mnuV;
    private javax.swing.JMenuItem mnuVA;
    // End of variables declaration//GEN-END:variables
}
